stages:
  - restart

variables:
  DEMO: "demo"

# Restart deploy
restart_deploy:
  stage: restart
  image: ubuntu:latest 
  before_script:
    - apt-get update -y && apt-get install -y curl unzip
    # Instala o 1Password CLI
    - |
      OP_VERSION="v2.30.0"
      curl -sSfo op.zip \
        "https://cache.agilebits.com/dist/1P/op2/pkg/${OP_VERSION}/op_linux_amd64_${OP_VERSION}.zip"
      unzip -o op.zip -d /usr/local/bin/
      rm op.zip
      op --version
      
      echo "before_script"
  script:
      echo "script"
      echo $INFRA_OP_SECRET_PASSWORD | op account add --address $INFRA_OP_SECRET_ADDRESS --email $INFRA_OP_SECRET_EMAIL
      eval $(echo $INFRA_OP_SECRET_PASSWORD | op signin --account $INFRA_OP_SECRET_ADDRESS)

      export ONE_PASSWORD_ITEM_NAME="Hostinger-Farmácia Clínica"
      export ONE_PASSWORD_ITEM_ID=$(op item get "$ONE_PASSWORD_ITEM_NAME" --format json | jq -r '.id')

      echo "-->$ONE_PASSWORD_ITEM_ID"


    # adicione seus comandos de deploy aqui