import {
	ManageCashbackDetails,
	ManageCashbackInterface,
} from '@app/modules/admin/cashback/models/manage-cashback.interface';
import {StatusEnum} from '@app/utils/status.enum';

export const cashbacks: ManageCashbackInterface[] = [
	{
		id: '978',
		exitStoreUser:
			'0 - Referral Commission on First Confirmed Transaction - Luis (luis@tagpeak.com)',
		date: '2024-09-23',
		title: 'Referral Commission',
		orderValue: 0,
		networkCommission: 0,
		currentReward: 5.0,
		priceDayZero: 0,
		isin: '',
		status: StatusEnum.FINISHED,
	},
	{
		id: '977',
		exitStoreUser: '3454 - Booking.com - Elsa Durães (duraes.elsa@gmail.com)',
		date: '2024-09-23',
		title: 'test elsa',
		orderValue: 850,
		networkCommission: 85,
		currentReward: 41.14,
		priceDayZero: 0,
		isin: '',
		status: StatusEnum.FINISHED,
	},
	{
		id: '976',
		exitStoreUser: 'Referral Bonus - Lu',
		date: '2024-09-23',
		title: 'Referral Bonus',
		orderValue: 0,
		networkCommission: 0,
		currentReward: 3.96,
		priceDayZero: 0,
		isin: '',
		status: StatusEnum.FINISHED,
	},
	{
		id: '975',
		exitStoreUser: 'Referral Bonus - Lu',
		date: '2024-09-23',
		title: 'Referral Bonus',
		orderValue: 0,
		networkCommission: 0,
		currentReward: 3.3,
		priceDayZero: 0,
		isin: '',
		status: StatusEnum.FINISHED,
	},
	{
		id: '974',
		exitStoreUser:
			'0 - Referral Commission on First Confirmed Transaction - Lu (luismariacabral@hotmail.com)',
		date: '2024-09-23',
		title: 'Referral Bonus',
		orderValue: 0,
		networkCommission: 0,
		currentReward: 3.3,
		priceDayZero: 0,
		isin: '',
		status: StatusEnum.FINISHED,
	},
	{
		id: '967',
		exitStoreUser: '3453 - Auchan - Tes ambassador (luiscabral91@gmail.com)',
		date: '2024-09-23',
		title: 'Test Ambassador Flat Fee',
		orderValue: 750,
		networkCommission: 75,
		currentReward: 33.0,
		priceDayZero: 1,
		isin: 'DE002249',
		status: StatusEnum.FINISHED,
	},
	{
		id: '966',
		exitStoreUser: '3452 - Sport Zone - Ref Test (cabral.luismaria@gmail.com)',
		date: '2024-09-23',
		title: 'Test Ref Flat',
		orderValue: 500,
		networkCommission: 50,
		currentReward: 33.0,
		priceDayZero: 1,
		isin: '',
		status: StatusEnum.FINISHED,
	},
];

export const cashbacksDetails: ManageCashbackDetails[] = cashbacks.map((cashback) => ({
	...cashback,
	refId: 3488,
	currency: 'EUR',
	initialDate: '2024-10-28',
	endDate: '2025-03-21',
	isin: cashback.isin ? `https://www.onvista.de/derivate/Optionsscheine/${cashback.isin}` : '',
	details: '',
	cashback: 0,
	orderDate: '2024-10-28',
	overridePrice: 0.0,
	unit: 27.2,
	currentCashReward: 7.48,
}));
