swagger-ui.enabled=true
swagger-ui.js.url=/blog/swagger-ui/res/
swagger-ui.spec.url=/blog/swagger/${filename}
redoc.enabled=true
openapi-explorer.enabled=true
rapidoc.enabled=true
rapidoc.bg-color=#14191f
rapidoc.text-color=#aec2e0
rapidoc.sort-endpoints-by=method
