micronaut:
    http:
        services:
            images:
                urls:
                    - ${IMAGES_HOST:`http://localhost:8099`}
    application:
        name: msProducts
    security:
        authentication: bearer
        token:
            jwt:
                enabled: true
                signatures:
                    jwks:
                        keycloak:
                            url: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8090}/realms/${KEYCLOAK_REALM:gof}/protocol/openid-connect/certs
        oauth2.clients.keycloak:
            grant-type: password
            client-id: ${KEYCLOAK_CLIENT_ID:CHANGE_ME_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:CHANGE_ME_CLIENT_SECRET}
            authorization:
                url: http://${KEYCLOAK_HOST:CHANGE_ME_HOST}:${KEYCLOAK_PORT:CHANGE_ME_PORT}/realms/${KEYCLOAK_REALM:CHANGE_ME_REALM}/protocol/openid-connect/auth
        enabled: false
    server:
        cors:
            enabled: true
        port: ${PRODUCTS_PORT:8090}
    router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger
                mapping: /swagger/**
            swagger-ui:
                mapping: /swagger-ui/**
                paths: classpath:META-INF/swagger/views/swagger-ui
netty:
    default:
        allocator:
            max-order: 3
datasources:
    default:
        url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:products}
        username: ${POSTGRES_USER:postgres}
        password: ${POSTGRES_PASSWORD:postgres}
        driverClassName: org.postgresql.Driver
        dialect: POSTGRES

jpa:
    default:
        properties:
            hibernate:
                hbm2ddl:
                    auto: update

files:
    directory: ${PRODUCT_FILES:.temp/ms-products/files}
    file-type:
        image:
            directory: images
            size: 5MB
            allowed-formats: [ "image/png", "image/jpg", "image/jpeg" ]
        video:
            directory: videos
            size: 40MB
            allowed-formats: [ "video/mp4" ]
        document:
            directory: documents
            size: 5MB
            allowed-formats: [ "application/pdf" ]
