FROM openjdk:17-alpine
WORKDIR /home/app
COPY ./build/docker/main/layers/libs /home/app/libs
COPY ./build/docker/main/layers/classes /home/app/classes
COPY ./build/docker/main/layers/resources /home/app/resources
COPY ./build/docker/main/layers/application.jar /home/app/application.jar


RUN rm -rf ms-firebase/src/main/resources/firebase-credentials.json
COPY firebase-credentials.json ms-firebase/credentials

EXPOSE 8083
ENTRYPOINT ["java", "-jar", "/home/app/application.jar"]
