-- +goose Up
-- +goose StatementBegin
SELECT 'up SQL query';

CREATE TABLE IF NOT EXISTS country
(
    uuid         UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    abbreviation TEXT,
    currency     TEXT,
    flag         TEXT,
    name         TEXT,
    enabled      boolean          default true,
    deleted      boolean          default false,
    created_at   TIMESTAMP(6),
    created_by   TEXT,
    updated_at   TIMESTAMP(6),
    updated_by   TEXT,
    deleted_at   TIMESTAMP(6),
    deleted_by   TEXT
);

-- +goose StatementEnd
INSERT INTO country (created_at, updated_at, abbreviation, created_by, currency, flag, name, updated_by)
VALUES (NOW(), NOW(), 'AR', 'system', 'ARS', null, 'Argentina', 'system'),
       (NOW(), NOW(), 'AU', 'system', 'AUD', null, 'Australia', 'system'),
       (NOW(), NOW(), 'AT', 'system', 'EUR', null, 'Austria', 'system'),
       (NOW(), NOW(), 'BE', 'system', 'EUR', null, 'Belgium', 'system'),
       (NOW(), NOW(), 'BO', 'system', 'BOB', null, 'Bolivia', 'system'),
       (NOW(), NOW(), 'BR', 'system', 'BRL', null, 'Brazil', 'system'),
       (NOW(), NOW(), 'BG', 'system', 'BGN', null, 'Bulgaria', 'system'),
       (NOW(), NOW(), 'CA', 'system', 'CAD', null, 'Canada', 'system'),
       (NOW(), NOW(), 'CL', 'system', 'CLP', null, 'Chile', 'system'),
       (NOW(), NOW(), 'CN', 'system', 'CNY', null, 'China', 'system'),
       (NOW(), NOW(), 'CO', 'system', 'COP', null, 'Colombia', 'system'),
       (NOW(), NOW(), 'HR', 'system', 'EUR', null, 'Croatia', 'system'),
       (NOW(), NOW(), 'CZ', 'system', 'CZK', null, 'Czech Republic', 'system'),
       (NOW(), NOW(), 'DK', 'system', 'DKK', null, 'Denmark', 'system'),
       (NOW(), NOW(), 'EC', 'system', 'USD', null, 'Ecuador', 'system'),
       (NOW(), NOW(), 'EG', 'system', 'EGP', null, 'Egypt', 'system'),
       (NOW(), NOW(), 'EE', 'system', 'EUR', null, 'Estonia', 'system'),
       (NOW(), NOW(), 'FI', 'system', 'EUR', null, 'Finland', 'system'),
       (NOW(), NOW(), 'FR', 'system', 'EUR', null, 'France', 'system'),
       (NOW(), NOW(), 'DE', 'system', 'EUR', null, 'Germany', 'system'),
       (NOW(), NOW(), 'GR', 'system', 'EUR', null, 'Greece', 'system'),
       (NOW(), NOW(), 'HU', 'system', 'HUF', null, 'Hungary', 'system'),
       (NOW(), NOW(), 'IS', 'system', 'ISK', null, 'Iceland', 'system'),
       (NOW(), NOW(), 'IN', 'system', 'INR', null, 'India', 'system'),
       (NOW(), NOW(), 'ID', 'system', 'IDR', null, 'Indonesia', 'system'),
       (NOW(), NOW(), 'IE', 'system', 'EUR', null, 'Ireland', 'system'),
       (NOW(), NOW(), 'IL', 'system', 'ILS', null, 'Israel', 'system'),
       (NOW(), NOW(), 'IT', 'system', 'EUR', null, 'Italy', 'system'),
       (NOW(), NOW(), 'JM', 'system', 'JMD', null, 'Jamaica', 'system'),
       (NOW(), NOW(), 'JP', 'system', 'JPY', null, 'Japan', 'system'),
       (NOW(), NOW(), 'KW', 'system', 'KWD', null, 'Kuwait', 'system'),
       (NOW(), NOW(), 'LV', 'system', 'EUR', null, 'Latvia', 'system'),
       (NOW(), NOW(), 'LI', 'system', 'CHF', null, 'Liechtenstein', 'system'),
       (NOW(), NOW(), 'LT', 'system', 'EUR', null, 'Lithuania', 'system'),
       (NOW(), NOW(), 'LU', 'system', 'EUR', null, 'Luxembourg', 'system'),
       (NOW(), NOW(), 'MY', 'system', 'MYR', null, 'Malaysia', 'system'),
       (NOW(), NOW(), 'MX', 'system', 'MXN', null, 'Mexico', 'system'),
       (NOW(), NOW(), 'MC', 'system', 'EUR', null, 'Monaco', 'system'),
       (NOW(), NOW(), 'MA', 'system', 'MAD', null, 'Morocco', 'system'),
       (NOW(), NOW(), 'NL', 'system', 'EUR', null, 'Netherlands', 'system'),
       (NOW(), NOW(), 'NZ', 'system', 'NZD', null, 'New Zealand', 'system'),
       (NOW(), NOW(), 'NO', 'system', 'NOK', null, 'Norway', 'system'),
       (NOW(), NOW(), 'PK', 'system', 'PKR', null, 'Pakistan', 'system'),
       (NOW(), NOW(), 'PY', 'system', 'PYG', null, 'Paraguay', 'system'),
       (NOW(), NOW(), 'PE', 'system', 'PEN', null, 'Peru', 'system'),
       (NOW(), NOW(), 'PH', 'system', 'PHP', null, 'Philippines', 'system'),
       (NOW(), NOW(), 'PL', 'system', 'PLN', null, 'Poland', 'system'),
       (NOW(), NOW(), 'PT', 'system', 'EUR', null, 'Portugal', 'system'),
       (NOW(), NOW(), 'QA', 'system', 'QAR', null, 'Qatar', 'system'),
       (NOW(), NOW(), 'RO', 'system', 'RON', null, 'Romania', 'system'),
       (NOW(), NOW(), 'RU', 'system', 'RUB', null, 'Russia', 'system'),
       (NOW(), NOW(), 'SA', 'system', 'SAR', null, 'Saudi Arabia', 'system'),
       (NOW(), NOW(), 'RS', 'system', 'RSD', null, 'Serbia', 'system'),
       (NOW(), NOW(), 'SG', 'system', 'SGD', null, 'Singapore', 'system'),
       (NOW(), NOW(), 'SK', 'system', 'EUR', null, 'Slovakia', 'system'),
       (NOW(), NOW(), 'SI', 'system', 'EUR', null, 'Slovenia', 'system'),
       (NOW(), NOW(), 'ZA', 'system', 'ZAR', null, 'South Africa', 'system'),
       (NOW(), NOW(), 'KR', 'system', 'KRW', null, 'South Korea', 'system'),
       (NOW(), NOW(), 'ES', 'system', 'EUR', null, 'Spain', 'system'),
       (NOW(), NOW(), 'SE', 'system', 'SEK', null, 'Sweden', 'system'),
       (NOW(), NOW(), 'CH', 'system', 'CHF', null, 'Switzerland', 'system'),
       (NOW(), NOW(), 'TH', 'system', 'THB', null, 'Thailand', 'system'),
       (NOW(), NOW(), 'TR', 'system', 'TRY', null, 'Turkey', 'system'),
       (NOW(), NOW(), 'UA', 'system', 'UAH', null, 'Ukraine', 'system'),
       (NOW(), NOW(), 'AE', 'system', 'AED', null, 'United Arab Emirates', 'system'),
       (NOW(), NOW(), 'GB', 'system', 'GBP', null, 'United Kingdom', 'system'),
       (NOW(), NOW(), 'US', 'system', 'USD', null, 'United States', 'system'),
       (NOW(), NOW(), 'VE', 'system', 'VES', null, 'Venezuela', 'system');

-- +goose Down
-- +goose StatementBegin
SELECT 'down SQL query';
-- +goose StatementEnd
