// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBryVQZZ8MsnvGGhq96XMlgEafvQ7wuJ4U',
    appId: '1:509240225527:web:e015a320db03bde4466df2',
    messagingSenderId: '509240225527',
    projectId: 'tagpeak-test',
    authDomain: 'tagpeak-test.firebaseapp.com',
    storageBucket: 'tagpeak-test.firebasestorage.app',
    measurementId: 'G-ML325X3LFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7X2R3HwJ4c1yT73PgFC4mVW8oUSmqWA0',
    appId: '1:509240225527:android:570f65983bd5f238466df2',
    messagingSenderId: '509240225527',
    projectId: 'tagpeak-test',
    storageBucket: 'tagpeak-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVXB6pajYEROtAvZqXmdj76841lcM_hA8',
    appId: '1:509240225527:ios:496fdbb437cd6746466df2',
    messagingSenderId: '509240225527',
    projectId: 'tagpeak-test',
    storageBucket: 'tagpeak-test.firebasestorage.app',
    iosBundleId: 'pt.atlanse.tagpeak.dev',
  );
}
